// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} className
 * @param {MxObject} boundingBox
 * @param {MxObject} customLabel
 * @param {Big} highConfidenceThreshold
 * @param {Big} mediumConfidenceThreshold
 * @returns {Promise.<void>}
 */
export async function JS_AddBoundingBox(className, boundingBox, customLabel, highConfidenceThreshold, mediumConfidenceThreshold) {
	// BEGIN USER CODE
	if (typeof boundingBox !== 'undefined' && typeof customLabel !== 'undefined'){
			var container = document.getElementsByClassName(className)[0];
			var confidence = customLabel.get("Confidence");
			var top = boundingBox.get("Top");
			var left = boundingBox.get("Left");
			var height = boundingBox.get("Height");
			var width = boundingBox.get("Width");

			var highlight = document.createElement("div");
			highlight.title = customLabel.get("Name") + " - "+ confidence +'%';
			highlight.classList.add("img-highlight");
			if(confidence > highConfidenceThreshold){highlight.classList.add("high-confidence");}
			else if(confidence >= mediumConfidenceThreshold){highlight.classList.add("medium-confidence");}
			else{highlight.classList.add("low-confidence");}


			highlight.style.top = (top*100) + "%";
			highlight.style.left = (left*100) + "%";
			highlight.style.width = (width*100) + "%";
			highlight.style.height = (height*100) + "%";
			container.append(highlight);
	}
	// END USER CODE
}
